#!/bin/bash
case "$2" in
  vpn-up)
    sysctl -w net.ipv6.conf.enp3s0.disable_ipv6=1
    sysctl -w net.ipv6.conf.wlp4s0.disable_ipv6=1
  ;;
  vpn-down)
    sysctl -w net.ipv6.conf.enp3s0.disable_ipv6=0
    sysctl -w net.ipv6.conf.wlp4s0.disable_ipv6=0
  ;;
esac
